### ISSUE TITLE
El archivo principal de nuestro proyecto siempre se debe llamar index.html

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-smartsies#2]

**Comment by smartsies** [comment]
me di cuenta nada más enviarlo 🙈 Es lo que pasa al copiar y pegar los archivos de otro ejercicio... Gracias por el feedback, Carlos, corrijo y termino el ejercicio siguiendo el esquema que has enviado, que me viene muy bien.
